name: Terraform

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v1
    - name: Install Terraform
      run: |
        sudo apt-get install unzip
        wget https://releases.hashicorp.com/terraform/0.12.8/terraform_0.12.8_linux_amd64.zip
        unzip terraform_0.12.8_linux_amd64.zip
        sudo mv terraform /usr/local/bin
    - name: Terraform Test
      run: |
        terraform init
        terraform validate
